//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App9.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App9.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not selected.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string text_add {
            get {
                return ResourceManager.GetString("text_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agreed.
        /// </summary>
        internal static string text_agreed {
            get {
                return ResourceManager.GetString("text_agreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All authors of the work.
        /// </summary>
        internal static string text_all_autors {
            get {
                return ResourceManager.GetString("text_all_autors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application geography.
        /// </summary>
        internal static string text_app_geogr {
            get {
                return ResourceManager.GetString("text_app_geogr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autors.
        /// </summary>
        internal static string text_autors {
            get {
                return ResourceManager.GetString("text_autors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string text_cancel {
            get {
                return ResourceManager.GetString("text_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change.
        /// </summary>
        internal static string text_change {
            get {
                return ResourceManager.GetString("text_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        internal static string text_choose {
            get {
                return ResourceManager.GetString("text_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a direction.
        /// </summary>
        internal static string text_choose_direction {
            get {
                return ResourceManager.GetString("text_choose_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose file.
        /// </summary>
        internal static string text_Choose_file {
            get {
                return ResourceManager.GetString("text_Choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dell.
        /// </summary>
        internal static string text_dell {
            get {
                return ResourceManager.GetString("text_dell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direction.
        /// </summary>
        internal static string text_direction {
            get {
                return ResourceManager.GetString("text_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download work.
        /// </summary>
        internal static string text_download {
            get {
                return ResourceManager.GetString("text_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draft.
        /// </summary>
        internal static string text_draft {
            get {
                return ResourceManager.GetString("text_draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the authors.
        /// </summary>
        internal static string text_enter_authors {
            get {
                return ResourceManager.GetString("text_enter_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the napravlinie.
        /// </summary>
        internal static string text_enter_naprav {
            get {
                return ResourceManager.GetString("text_enter_naprav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the organization.
        /// </summary>
        internal static string text_enter_org {
            get {
                return ResourceManager.GetString("text_enter_org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the work name.
        /// </summary>
        internal static string text_enter_work_name {
            get {
                return ResourceManager.GetString("text_enter_work_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string text_error {
            get {
                return ResourceManager.GetString("text_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong. Apparently an incorrect link..
        /// </summary>
        internal static string text_link_error {
            get {
                return ResourceManager.GetString("text_link_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maps.
        /// </summary>
        internal static string text_maps {
            get {
                return ResourceManager.GetString("text_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Application.
        /// </summary>
        internal static string text_newApplication {
            get {
                return ResourceManager.GetString("text_newApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string text_ok {
            get {
                return ResourceManager.GetString("text_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open work.
        /// </summary>
        internal static string text_open_file {
            get {
                return ResourceManager.GetString("text_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Organization.
        /// </summary>
        internal static string text_organization {
            get {
                return ResourceManager.GetString("text_organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Responsible organization.
        /// </summary>
        internal static string text_organization_woks {
            get {
                return ResourceManager.GetString("text_organization_woks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt Save Successfully.
        /// </summary>
        internal static string text_prompt_save {
            get {
                return ResourceManager.GetString("text_prompt_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prompt Added Successfully.
        /// </summary>
        internal static string text_prompt_sent {
            get {
                return ResourceManager.GetString("text_prompt_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string text_save {
            get {
                return ResourceManager.GetString("text_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent.
        /// </summary>
        internal static string text_sent {
            get {
                return ResourceManager.GetString("text_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent.
        /// </summary>
        internal static string text_sented {
            get {
                return ResourceManager.GetString("text_sented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string text_success {
            get {
                return ResourceManager.GetString("text_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong. Please try again.
        /// </summary>
        internal static string text_try_again {
            get {
                return ResourceManager.GetString("text_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work name.
        /// </summary>
        internal static string text_work_name {
            get {
                return ResourceManager.GetString("text_work_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full name of the work.
        /// </summary>
        internal static string text_work_name_full {
            get {
                return ResourceManager.GetString("text_work_name_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Work.
        /// </summary>
        internal static string text_works {
            get {
                return ResourceManager.GetString("text_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your request.
        /// </summary>
        internal static string text_your_request {
            get {
                return ResourceManager.GetString("text_your_request", resourceCulture);
            }
        }
    }
}
